---
- name: Configurar cliente NIS
  hosts: localhost
  connection: local
  tasks:
    - name: Instalar nis
      ansible.builtin.apt:
        name: nis
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: Editar o arquivo de configuração /etc/yp.conf
      ansible.builtin.copy:
        src: cliente_nis/files/yp.conf
        dest: /etc/yp.conf
        mode: "0644"

    - name: Definir o nome de domínio NIS no arquivo de configuração /etc/defaultdomain
      ansible.builtin.copy:
        src: cliente_nis/files/defaultdomain
        dest: /etc/defaultdomain
        mode: "0644"

    - name: Editar o arquivo de configuração /etc/nsswitch.conf [Ubuntu MATE 24]
      ansible.builtin.copy:
        src: cliente_nis/files/nsswitch_ubuntu-mate-24.conf
        dest: /etc/nsswitch.conf
        mode: "0644"
      when: is_ubuntu_24

    - name: Editar o arquivo de configuração /etc/nsswitch.conf [Linux Mint 22]
      ansible.builtin.copy:
        src: cliente_nis/files/nsswitch_linux-mint-22.conf
        dest: /etc/nsswitch.conf
        mode: "0644"
      when: is_mint_22

    - name: Reiniciar e ativar o serviço rpcbind
      ansible.builtin.systemd_service:
        name: rpcbind
        state: restarted
        enabled: true

    - name: Reiniciar e ativar o serviço nscd
      ansible.builtin.systemd_service:
        name: nscd
        state: restarted
        enabled: true

    - name: Reiniciar e ativar o serviço ypbind
      ansible.builtin.systemd_service:
        name: ypbind
        state: restarted
        enabled: true
