---
- name: Configuração adicional
  hosts: localhost
  connection: local
  tasks:
    - name: Editar o arquivo de configuração do servidor ssh /etc/sshd_config
      ansible.builtin.copy:
        src: ssh/files/sshd_config
        dest: /etc/sshd_config
        mode: "0644"
