---
- name: Configuração adicional
  hosts: localhost
  connection: local
  tasks:
    - name: Permitir login root usando ssh. Inserir arquivo de configuração /etc/ssh/sshd_config.d/99-allow-root-login.conf
      ansible.builtin.copy:
        src: ssh/files/99-allow-root-login.conf
        dest: /etc/ssh/sshd_config.d/99-allow-root-login.conf
        mode: "0644"
