---
- name: Configurar cliente NFS
  hosts: localhost
  connection: local
  tasks:
    - name: Instalar NFS (importar tasks)
      ansible.builtin.import_tasks:
        file: tasks/nfs_instalar.yml

    - name: Configurar NFS (importar tasks)
      ansible.builtin.import_tasks:
        file: tasks/nfs_atualizar.yml
