---
- name: Permitir login manual na tela de login LightDM
  hosts: localhost
  connection: local
  tasks:
    - name: Copiar arquivo de configuração adicional para /etc/lightdm/lighdm.conf.d/
      ansible.builtin.copy:
        src: files/50-myconfig.conf
        dest: /etc/lightdm/lightdm.conf.d/50-myconfig.conf
