---
- name: Verificar compatibilidade do sistema
  hosts: localhost
  pre_tasks:
    - name: Definir variáveis informando o sistema operacional
      ansible.builtin.set_fact:
        is_mint_22: >-
          {{ ansible_distribution == 'Linux Mint'
             and ansible_distribution_version is version('22', '>=')
             and ansible_distribution_version is version('23', '<') }}
        is_ubuntu_24: >-
          {{ ansible_distribution == 'Ubuntu'
             and ansible_distribution_version is version('24', '>=')
             and ansible_distribution_version is version('25', '<') }}

    - name: Falhar se o sistema operacional não for Linux Mint 22 ou Ubuntu 24
      ansible.builtin.fail:
        msg: Sistema operacional não suportado. Apenas Linux Mint 22 and Ubuntu 24 são suportados.
      when: not (is_mint_22 or is_ubuntu_24)

- import_playbook: 01_rede.yml
- import_playbook: 02_cliente_nfs.yml
- import_playbook: 03_cliente_nis.yml
- import_playbook: 04_tela_de_login.yml
- import_playbook: 05_instalar_apps.yml
- import_playbook: 06_ssh.yml
