---
- name: Configurar tela de login LightDM
  hosts: localhost
  connection: local
  tasks:
    - name: Desativar guest e exibir login manual (importar tasks)
      ansible.builtin.import_tasks:
        file: display_manager/tasks/lightdm_ubuntu_mate_24.yml
