---
- name: Atualizar lista de pacotes (apt-get update)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Instalar Google Chrome
  ansible.builtin.apt:
    deb: /dados/nis/Downloads/applications/google-chrome-stable_current_amd64.deb
