---
- name: Atualizar índice de pacotes apt
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Instalar pacotes APT
  ansible.builtin.apt:
    name:
      - build-essential
      - cmake
      - curl
      - default-jdk
      - default-jdk-doc
      - fzf
      - gedit
      - gnumeric
      - htop
      - neovim
      - openssh-client
      - openssh-server
      - pkg-config
      - parallel
      - pipx
      - silversearcher-ag
      - ssh
      - tmux
      - xterm
    state: present

- name: Instalar mint-meta-codecs [Linux Mint]
  ansible.builtin.apt:
    name: mint-meta-codecs
    state: present
  when: ansible_distribution == "Linux Mint"

- name: Instalar Google Chrome
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  when: "'google-chrome-stable' not in ansible_facts.packages"
